==============================\
Student name: Shiqi Yin \
GitHub username: acse-sy121\
\==============================

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import sys

# Scikit-Learn ≥0.20 is required
import sklearn
import os
os.chdir("/content/drive/MyDrive")
# Common imports
import numpy as np

In [ ]:
experimental = np.load('/content/drive/MyDrive/output_files/DATA/real_value.npy')

In [ ]:
print(experimental.shape)

(3, 120, 18)


In [ ]:
exp_CO2 = np.array(experimental[0])
exp_Humidity = np.array(experimental[1]*1e-2)
exp_Temperature = np.array(experimental[2]+273.15)

In [ ]:
exp_CO2[0]

array([794.43070175, 589.43070175, 683.43070175, 495.43070175,
       822.43070175, 702.43070175, 518.43070175, 712.43070175,
       878.43070175, 492.11403509, 521.43070175, 544.76403509,
       531.43070175, 522.43070175, 520.43070175, 505.43070175,
       512.43070175, 500.43070175])

In [ ]:
exp_Humidity[0]

array([0.43194355, 0.41094355, 0.39694355, 0.40194355, 0.42594355,
       0.41994355, 0.38524355, 0.39194355, 0.42494355, 0.39855855,
       0.39164355, 0.39236022, 0.40094355, 0.39334355, 0.39914355,
       0.40894355, 0.39094355, 0.39154355])

In [ ]:
exp_Temperature[0]

array([303.73390243, 304.93390243, 303.43390243, 302.33390243,
       303.13390243, 302.63390243, 303.42279132, 303.23390243,
       303.03390243, 305.06816169, 302.12834688, 302.72723577,
       303.74501354, 302.44501354, 302.77834688, 303.31723577,
       302.58945799, 303.23945799])

In [ ]:
def train_test_split(field_data):
  X_train_array = []
  X_test_array = []

  for i in range(int(len(field_data)*0.8)):
    X_train_array.append(field_data[i])
  X_train_array = np.array(X_train_array)

  for i in range(int(len(field_data)*0.8),len(field_data)):
    X_test_array.append(field_data[i])
  X_test_array = np.array(X_test_array)

  print("Train dataset shape: ", X_train_array.shape)
  print("Test dataset shape: ", X_test_array.shape)

  return X_train_array, X_test_array

In [ ]:
exp_CO2_train, exp_CO2_test = train_test_split(exp_CO2)
exp_Humidity_train, exp_Humidity_test = train_test_split(exp_Humidity)
exp_Temperature_train, exp_Temperature_test = train_test_split(exp_Temperature)

Train dataset shape:  (96, 18)
Test dataset shape:  (24, 18)
Train dataset shape:  (96, 18)
Test dataset shape:  (24, 18)
Train dataset shape:  (96, 18)
Test dataset shape:  (24, 18)


In [ ]:
from sklearn.preprocessing import MinMaxScaler
import joblib

In [ ]:
scaler_exp_CO2_all = joblib.load('/content/drive/MyDrive/output_files/scalers/sensor_data/scaler_ob_CO2_all.pkl')
scaler_exp_Humidity_all = joblib.load('/content/drive/MyDrive/output_files/scalers/sensor_data/scaler_ob_Humidity_all.pkl')
scaler_exp_Temperature_all = joblib.load('/content/drive/MyDrive/output_files/scalers/sensor_data/scaler_ob_Temperature_all.pkl')

In [ ]:
# scaler_exp_CO2 = MinMaxScaler((0, 1))
# scaler_exp_Humidity = MinMaxScaler((0, 1))
# scaler_exp_Temperature = MinMaxScaler((0, 1))

# scaler_exp_CO2_test = MinMaxScaler((0, 1))
# scaler_exp_Humidity_test = MinMaxScaler((0, 1))
# scaler_exp_Temperature_test = MinMaxScaler((0, 1))

# scaler_exp_CO2_all = MinMaxScaler((0, 1))
# scaler_exp_Humidity_all = MinMaxScaler((0, 1))
# scaler_exp_Temperature_all = MinMaxScaler((0, 1))

In [ ]:
# norm_exp_CO2_train = scaler_exp_CO2.fit_transform(exp_CO2_train)
# norm_exp_Humidity_train = scaler_exp_Humidity.fit_transform(exp_Humidity_train)
# norm_exp_Temperature_train = scaler_exp_Temperature.fit_transform(exp_Temperature_train)

# norm_exp_CO2_test = scaler_exp_CO2_test.fit_transform(exp_CO2_test)
# norm_exp_Humidity_test = scaler_exp_Humidity_test.fit_transform(exp_Humidity_test)
# norm_exp_Temperature_test = scaler_exp_Temperature_test.fit_transform(exp_Temperature_test)

norm_exp_CO2_all = scaler_exp_CO2_all.transform(exp_CO2)
norm_exp_Humidity_all = scaler_exp_Humidity_all.transform(exp_Humidity)
norm_exp_Temperature_all = scaler_exp_Temperature_all.transform(exp_Temperature)

In [ ]:
# train_exp_all_values = np.hstack((norm_exp_CO2_train, norm_exp_Humidity_train, norm_exp_Temperature_train))
# test_exp_all_values = np.hstack((norm_exp_CO2_test, norm_exp_Humidity_test, norm_exp_Temperature_test))
exp_all_values = np.hstack((norm_exp_CO2_all, norm_exp_Humidity_all, norm_exp_Temperature_all))

In [ ]:
exp_all_values.shape

(120, 54)

In [ ]:
import joblib
# Store the all data in the form of numpy.ndarray
# joblib.dump(train_exp_all_values, '/content/drive/MyDrive/output_files/DATA/data_used_for_model/experimental_train.pkl')
# joblib.dump(test_exp_all_values, '/content/drive/MyDrive/output_files/DATA/data_used_for_model/experimental_test.pkl')
joblib.dump(exp_all_values, '/content/drive/MyDrive/output_files/DATA/data_used_for_model/experimental.pkl')

# joblib.dump(scaler_exp_CO2, '/content/drive/MyDrive/output_files/scalers/experimental_data/scaler_exp_CO2.pkl')
# joblib.dump(scaler_exp_Humidity, '/content/drive/MyDrive/output_files/scalers/experimental_data/scaler_exp_Humidity.pkl')
# joblib.dump(scaler_exp_Temperature, '/content/drive/MyDrive/output_files/scalers/experimental_data/scaler_exp_Temperature.pkl')

# joblib.dump(scaler_exp_CO2_test, '/content/drive/MyDrive/output_files/scalers/experimental_data/scaler_exp_CO2_test.pkl')
# joblib.dump(scaler_exp_Humidity_test, '/content/drive/MyDrive/output_files/scalers/experimental_data/scaler_exp_Humidity_test.pkl')
# joblib.dump(scaler_exp_Temperature_test, '/content/drive/MyDrive/output_files/scalers/experimental_data/scaler_exp_Temperature_test.pkl')

# joblib.dump(scaler_exp_CO2_all, '/content/drive/MyDrive/output_files/scalers/experimental_data/scaler_exp_CO2_all.pkl')
# joblib.dump(scaler_exp_Humidity_all, '/content/drive/MyDrive/output_files/scalers/experimental_data/scaler_exp_Humidity_all.pkl')
# joblib.dump(scaler_exp_Temperature_all, '/content/drive/MyDrive/output_files/scalers/experimental_data/scaler_exp_Temperature_all.pkl')

['/content/drive/MyDrive/output_files/DATA/data_used_for_model/experimental.pkl']